### PR TITLE
Add Preloading Spinners to Cards

### LINKED ISSUE #4: Add preloading spinners to cards
The cards are initially empty when the subtitles are being fetched. This jumbles the layout and takes a bit of time for the website to take its final shape. Adding a preloader inside the cards may turn out to be helpful.

### PR DESCRIPTION
**Pull request by satyaim**
I want to resolve #4 . I'm adding pre-loading spinners to cards.

Changes Made
> Pre-loading spinners are rendered in channel-card having no captions.
> Loader does not render when caption is added (rendered).
> This is achieved by: If number of captions are zero, spinner gets rendered in place of captions table.

### CODE REVIEW

**Comment by saurabhshah0410** [comment]
@satyaim Congrats on your first PR! This comment is on the other aspects of PR apart from the changes. I think the commit messages can be better.

* The subject of the commit message should try to summarize the changes made in that commit in a single line, followed by an elaboration of the changes that you have proposed in the body of the message.

* Try to use the present tense as much as possible as opposed to the past tense.

* Also, if the last three commits of yours do some segments of the same thing logical thing (i.e, "Added Spinner"), it would make sense to squash those three commits into a single commit, so that logical changes are kept as a part of a single commit.

* Also, preferably, every file(source file at least) should end with a new line. So ideally you should use an editor that automatically adds newline at the end of the file on saving, or manually add a newline yourself.

Some good etiquettes on commit messages can be found here: https://chris.beams.io/posts/git-commit/

**Comment by satyaim** [comment]
@saurabhshah0410  Thanks for valuable suggestions. I've edited the comment accordingly and I'll keep this in mind during other PRs.
Btw, what about the proposed changes?

**Comment by saurabhshah0410** [comment]
@satyaim I can't comment on the proposed changes in your commits, as I am not a contributor to this repository.

**Comment by rkuchumov** [comment]
Well, you should start over.

1. package-lock.json is auto generated file and should be a part of your commit.

2. a single PR should change only one feature. From what I see you are trying to:

  *  change deployment configuration
  *  change indentations
  *  change MongoDB arguments
  *  replace double quotes with single quotes for some reason 
  *  render captions to the browser console

None of these are documented and explained in commit messages nor PR description.

3. The way you are adding spinner is incorrect, as you are rendering captions three times.

**Comment by satyaim** [comment]
Alright! I'll make the necessary changes!
However, I didn't get the third point, "The way you are adding spinner is incorrect, as you are rendering captions three times".
Captions are rendering the same way, the difference is that I've added "if condition" which either renders Captions, or Loader while rendering the Channel. (Loader is rendered only when the captions array returned by renderCaptions() is having length zero, i.e. no captions).

**Comment by rkuchumov** [comment]
I meant you are calling renderCaptions() 3 times. to dump it to the console, to check the condition, and then actually to render.
Application logic and rendering should not be mixed and what is more important, application logic should not depend on the rendering.

**Comment by satyaim** [comment]
And package-lock.json was in the commit. Should it not be there? There is no package-lock.json in ccr/admin in master.

**Comment by rkuchumov** [comment]
Ah, my bad, got distracted when I was writing that...
I'll add these files myself later, so, please, don't commit them.

**Pull request closed without merging**
